version: "2"
services:
  secure-tunnel-server:
    build:
      context: ../../../
      dockerfile: tunnel/cmd/secure-tunnel-server/Dockerfile
    command:
      - "/usr/local/bin/secure-tunnel-server"
      - "-mqtt-endpoint=${AWS_IOT_ENDPOINT}"
      # - "-generate-test-token"  # uncomment to generate token at beginning
    environment:
      - AWS_IOT_ENDPOINT
  tlsoffloading:
    build: tlsoffloading
    ports:
      - "443:443"
