name: go-mod-fix
on:
  push:
    branches:
      - renovate/*

jobs:
  go-mod-fix:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: fix
        uses: at-wat/go-sum-fix-action@v0
        with:
          git_user: sqbot
          git_email: 30003564+sqbot@users.noreply.github.com
          github_token: ${{ secrets.SQBOT_GITHUB_TOKEN }}
          commit_style: add
          push: yes
          check_no_indirect_diffs: false
          monorepos: |
            github.com/aws/aws-sdk-go-v2
