name: tunnel-server
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  tunnel-server:
    runs-on: ubuntu-latest
    steps:
      - name: Set image tag
        if: startsWith(github.ref, 'refs/tags')
        run: echo "IMAGE_TAG=${GITHUB_REF#refs/tags}" | tee -a ${GITHUB_ENV}

      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/aws-iot-secure-tunnel-server:${IMAGE_TAG:-devel} \
            -f ./tunnel/cmd/secure-tunnel-server/Dockerfile .

      - name: Login to GitHub Container Registry
        if: startsWith(github.ref, 'refs/tags')
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
      - name: Push to GitHub Container Registry
        if: startsWith(github.ref, 'refs/tags')
        run: docker push ghcr.io/${{ github.repository_owner }}/aws-iot-secure-tunnel-server:${IMAGE_TAG:-devel}
