name: tunnel-server
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  tunnel-server:
    runs-on: ubuntu-latest
    steps:
      - name: Set image tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "IMAGE_TAG=${GITHUB_REF#refs/tags/v}" | tee -a ${GITHUB_ENV}

      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker build
        run: |
          docker build \
            -t aws-iot-secure-tunnel-server \
            -f ./tunnel/cmd/secure-tunnel-server/Dockerfile .

      - name: Login to GitHub Container Registry
        if: startsWith(github.ref, 'refs/tags')
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Container Registry
        if: startsWith(github.ref, 'refs/tags')
        run: |
          image=ghcr.io/${{ github.repository_owner }}/aws-iot-secure-tunnel-server
          docker tag aws-iot-secure-tunnel-server ${image}:${IMAGE_TAG:-devel}
          docker tag aws-iot-secure-tunnel-server ${image}:latest
          docker push ${image}:${IMAGE_TAG:-devel}
          docker push ${image}:latest
          docker logout ghcr.io

      - name: Login to ECR public
        if: startsWith(github.ref, 'refs/tags')
        uses: docker/login-action@v2
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Push to ECR public
        if: startsWith(github.ref, 'refs/tags')
        run: |
          image=public.ecr.aws/${{ secrets.AWS_ECR_PUBLIC_ALIAS }}/aws-iot-secure-tunnel-server
          docker tag aws-iot-secure-tunnel-server ${image}:${IMAGE_TAG:-devel}
          docker tag aws-iot-secure-tunnel-server ${image}:latest
          docker push ${image}:${IMAGE_TAG:-devel}
          docker push ${image}:latest
          docker logout public.ecr.aws
